version: '3.8'

services:
  api-service:
    build:
      context: .
      target: development
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
      - PORT=4000
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped

  # Production service configuration
  api-service-prod:
    build:
      context: .
      target: production
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - PORT=4000
    env_file:
      - .env
    restart: unless-stopped
    profiles:
      - production

networks:
  default:
    name: bmnr-api-network